time: 2017-07-07 14:23:55.495025Z
tags: worker-0
test: setUpClass (tests.ScenarioNoError)
time: 2017-07-07 14:23:55.495025Z
failure: setUpClass (tests.ScenarioNoError) [ multipart
Content-Type: text/x-traceback;charset=utf8,language=python
traceback
447
Traceback (most recent call last):
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/base.py", line 144, in setUpClass
    cls.prepare_instance()
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/base.py", line 162, in prepare_instance
    cls.prepare_recipe()
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/cloud/base.py", line 31, in prepare_recipe
    return cls.recipe.prepare(service_type=cls.service_type)
  File "/root/workspace/cloudbase-init-ci/argus/recipes/cloud/base.py", line 192, in prepare
    self.prepare_cbinit_config(service_type)
  File "/root/workspace/cloudbase-init-ci/argus/recipes/cloud/windows.py", line 301, in prepare_cbinit_config
    self._cbinit_conf.set_service_type(service_type)
  File "/root/workspace/cloudbase-init-ci/argus/config_generator/windows/cb_init.py", line 117, in set_service_type
    service_type = [self._get_service(serv) for serv in service_type]
  File "/root/workspace/cloudbase-init-ci/argus/config_generator/windows/cb_init.py", line 96, in _get_service
    if self.SERVICES[service_type]:
KeyError: 'noservice'
0
]
tags: -worker-0
