time: 2017-07-03 16:44:26.178468Z
tags: worker-0
test: setUpClass (tests.ScenarioNoError)
time: 2017-07-03 16:44:26.178468Z
failure: setUpClass (tests.ScenarioNoError) [ multipart
Content-Type: text/x-traceback;charset=utf8,language=python
traceback
460
Traceback (most recent call last):
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/base.py", line 144, in setUpClass
    cls.prepare_instance()
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/base.py", line 162, in prepare_instance
    cls.prepare_recipe()
  File "/root/workspace/cloudbase-init-ci/argus/scenarios/cloud/base.py", line 31, in prepare_recipe
    return cls.recipe.prepare(service_type=cls.service_type)
  File "/root/workspace/cloudbase-init-ci/argus/recipes/cloud/base.py", line 184, in prepare
    self.wait_for_boot_completion()
  File "/root/workspace/cloudbase-init-ci/argus/recipes/cloud/windows.py", line 51, in wait_for_boot_completion
    self._backend.remote_client.manager.wait_boot_completion()
  File "/root/workspace/cloudbase-init-ci/argus/util.py", line 265, in __get__
    instance.__dict__[self.name] = result = self.func(instance)
  File "/root/workspace/cloudbase-init-ci/argus/backends/local/local_backend.py", line 28, in get_remote_client
    return windows.WinRemoteClient(self.floating_ip(),
AttributeError: 'module' object has no attribute 'WinRemoteClient'
0
]
tags: -worker-0
